# Generated by Django 4.2.6 on 2024-08-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='profile.jpg', upload_to='media/uploads/images')),
                ('title', models.CharField(default='Default Name', max_length=255)),
                ('category', models.TextField(default='Uncategorized')),
                ('description', models.TextField()),
            ],
        ),
    ]
